# 配置文件模板 - 请复制此文件为 application-local.yml 并填入真实配置信息
server:
  port: 8101

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: YOUR_RABBITMQ_USERNAME
  password: YOUR_RABBITMQ_PASSWORD

yuapi:
  client:
    api-key: YOUR_API_KEY
    secret-key: YOUR_SECRET_KEY

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD
    url: jdbc:mysql://localhost:3306/YOUR_DATABASE_NAME?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  
  # 邮箱配置
  mail:
    host: smtp.qq.com
    port: 587
    username: YOUR_EMAIL@qq.com
    password: YOUR_EMAIL_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    password: YOUR_REDIS_PASSWORD # 如果有密码的话

# 其他配置... 